### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by oh2xx** [ArduinoMax/MCP41xxx#2]
C:\Users\Kari\Documents\Arduino\libraries\MCP41XXX\src\MCP41xxx.cpp: In member function 'void MCP41xxx::analogWrite(uint8_t, uint16_t)':

C:\Users\Kari\Documents\Arduino\libraries\MCP41XXX\src\MCP41xxx.cpp:35:15: error: 'ADC_SHUTDOWN' was not declared in this scope

  if (value == ADC_SHUTDOWN)

```
           ^
```
# 

There seems to be a typing error: ADC_SHUTDOWN should be DAC_SHUTDOWN

**Comment by xcvista** [comment]
Fixed in v1.0.4
