### ISSUE TITLE
problems in Arduino Library Manager

### ISSUE THREAD

**Issue by ponty** [ArduinoMax/MCP41xxx#4]
Please publish the latest version.
The current version in Arduino Library Manager is 1.0.3 which has 
the typing error: ADC_SHUTDOWN should be DAC_SHUTDOWN (#2)

Please change version in your library.properties.

Other problem:
After I installed the lib it duplicated itself in the Library Manager view.
It can be a name mismatch:
   "ArduMax MCP41xxx" <-> "MCP41xxx"

![library manager_017](https://cloud.githubusercontent.com/assets/584643/25121761/0cf73cee-2423-11e7-8368-e0c7d022b69c.png)

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by xcvista** [comment]
I have fixed that in the 1.0.6 but Arduino folks did not pick up.

**Comment by ponty** [comment]
According to Arduino Library-Manager-FAQ the update is automatic.

https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

"How can I publish a new release once my library is in the list?

Ensure you've changed version in your library.properties. Then tag your library once more and push the new tag (or create a release if your web hosting offers a way to do it, for example with GitHub "releases"). Our indexer checks for new releases every hour and will eventually fetch and publish your new release.
"

**Comment by xcvista** [comment]
@ponty I have pumped the version number to 1.0.6. Let's see when Arduino would pick it up.

**Comment by ponty** [comment]
It's OK
